name: Run the Kemocade VRChat Group Maker Action

on:
  # Runs every hour at XX:30 by default
  schedule:
    - cron: '30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  group:
    runs-on: ubuntu-latest
    steps:
      - name: Kemocade VRChat Group Maker Action
        uses: kemocade/Kemocade.Vrc.Maker.Tracker.Action@1.0.0
        with:
          output: ${{ env.output }}
          username: ${{ vars.VRCHAT_USERNAME }}
          password: ${{ secrets.VRCHAT_PASSWORD }}
          key: ${{ secrets.VRCHAT_KEY }}
          shortcode: ${{ env.VRCHAT_SHORTCODE }}
          discriminators: ${{ env.VRCHAT_DISCRIMINATORS }}