name: Run the Kemocade VRChat Group Maker Action

on:
  # Runs every hour at XX:30 by default
  schedule:
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  group:
    runs-on: ubuntu-latest
    steps:
      - name: Kemocade VRChat Group Maker Action
        uses: kemocade/Kemocade.Vrc.Group.Maker.Action@1.0.4
        with:
          username: ${{ vars.VRCHAT_USERNAME }}
          password: ${{ secrets.VRCHAT_PASSWORD }}
          key: ${{ secrets.VRCHAT_KEY }}
          name: ${{ vars.VRCHAT_NAME }}
          shortcode: ${{ vars.VRCHAT_SHORTCODE }}
          discriminators: ${{ vars.VRCHAT_DISCRIMINATORS }}
